In [2]:
import pandas as pd


In [3]:
df_1  = pd.read_excel("df-taller2.xlsx", sheet_name="Hoja1")

In [4]:
df_2 = pd.read_excel("df-taller2.xlsx", sheet_name="Hoja2")

In [5]:
#df_1.info()
for col in  df_1.columns:
  print(df_1[col].value_counts(normalize=True))

Dpto
5     0.380952
11    0.380952
41    0.238095
Name: proportion, dtype: float64
MPIO
411    0.238095
51     0.190476
52     0.190476
111    0.142857
112    0.142857
113    0.095238
Name: proportion, dtype: float64
Causa_667
305    0.571429
102    0.428571
Name: proportion, dtype: float64


In [6]:
df_2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Municpio  8 non-null      int64
 1   pop       8 non-null      int64
dtypes: int64(2)
memory usage: 256.0 bytes


In [7]:
df_2.columns

Index(['Municpio', 'pop'], dtype='object')

In [8]:
df_2['Municpio'].value_counts()

Municpio
781    2
52     1
51     1
411    1
111    1
113    1
112    1
Name: count, dtype: int64

In [9]:
df_2['pop'].describe()

count     8.000000
mean     43.375000
std      29.144652
min      12.000000
25%      19.750000
50%      35.000000
75%      72.500000
max      80.000000
Name: pop, dtype: float64

In [10]:
print(df_1.columns)
print(df_2.columns)

Index(['Dpto', 'MPIO', 'Causa_667'], dtype='object')
Index(['Municpio', 'pop'], dtype='object')


In [11]:
df_1['MPIO'].unique()

array([ 51,  52, 411, 111, 112, 113])

In [12]:
df_2['Municpio'].unique()

array([ 51,  52, 411, 111, 113, 112, 781])

In [13]:
df_1['Dpto'].unique()

array([ 5, 41, 11])

In [14]:
def extract(string):
  if len(string)==2:
    return string[0]
  else:
    return string[0:2]

In [15]:
set(df_1['MPIO'].unique()) - set(df_2['Municpio'].unique())

set()

In [16]:
set(df_2['Municpio'].unique()) - set(df_1['MPIO'].unique())

{np.int64(781)}

In [17]:
df_1['muertes']  = df_1.groupby(by=['Dpto','Causa_667']).transform('count')

In [18]:
df_1 = df_1[-df_1.duplicated(subset=['Dpto', 'Causa_667'])]

In [19]:
df_2['Dpto']  = df_2['Municpio'].apply(lambda x: int(extract(str(x))))
df_2['totalpop'] = df_2.groupby(by=['Dpto'])['pop'].transform('sum')

In [20]:
df_2 = df_2[['Dpto','totalpop']].copy()
df_2 = df_2[-df_2.duplicated(subset=['Dpto'])]

In [21]:
full = df_1.merge(df_2, on='Dpto')

In [22]:
full['rates'] = (full['muertes']/full['totalpop'])*100

In [23]:
full

Dpto  MPIO  Causa_667  muertes  totalpop     rates
0     5    51        102        5        70  7.142857
1     5    52        305        3        70  4.285714
2    41   411        305        5        70  7.142857
3    11   111        305        4        47  8.510638
4    11   111        102        4        47  8.510638